export const CONSTANTS = {
  TILE_SIZE: 2,
  NETWORK_PER_PANEL: 0.7,
  HALF_CAB_STEP: 1.8,
  QUARTER_CAB_STEP: 1.8,
  METERS_PER_FOOT: 0.3048,
  U_HEIGHT_INCHES: 1.75,
  CABINET_BASE_HEIGHT: 4,
  MAX_SLACK: 100,
} as const;
